Rely on updated pkgbuild::needs_compilation()
extendr/rextendr pull request #221
Opened 2022-12-18 07:17 UTC by yutannihilation

Fix #215

(Sorry, I mistakenly committed this directly to the main branch... I reverted)

2022-12-18 09:40 UTC, Ilia-Kosenkov commented
Should `track_rust_source` file be removed completely? Do we use its functions anywhere else?


Also, I believe it is worth updating the changelog.

2022-12-18 10:45 UTC, yutannihilation commented
Oh, it might be. I'll try it.

I'm still figuring out, but I think this doesn't introduce any user-visible changes. What do you think?

2022-12-18 10:49 UTC, Ilia-Kosenkov commented
Hm, you are correct. We used pkgbuild before. The only visible change is the minimum required version :)

2022-12-18 11:07 UTC, yutannihilation commented
Yeah. One notable progress is that the developers now can just press the "Load all" menu of RStudio as long as no signatures are changed. But this is not our archivement...

2022-12-18 12:26 UTC, yutannihilation commented
> Should `track_rust_source` file be removed completely? Do we use its functions anywhere else?

I checked. In short, there's not many functions that can be removed.

`pretty_rel_path()` is used here; `pretty_rel_single_path()` and `on_error_return_default()` are used inside the function.

https://github.com/extendr/rextendr/blob/ae38dfc0ffa3fef294fc97424c7c19580968a787/R/register_extendr.R#L89

`get_library_path()` is used here.

https://github.com/extendr/rextendr/blob/ae38dfc0ffa3fef294fc97424c7c19580968a787/R/register_extendr.R#L68

`find_newer_files_than()` is used here `get_file_info()` is used inside the function.

https://github.com/extendr/rextendr/blob/ae38dfc0ffa3fef294fc97424c7c19580968a787/R/register_extendr.R#L88

2022-12-22 10:44 UTC, Ilia-Kosenkov commented
Sorry I missed your comment here. It feels like `get_file_info()` should no longer be used?

2022-12-22 10:51 UTC, yutannihilation commented
No, I meant `get_file_info()` is used in `find_newer_files_than()`, which is used in `register_extendr()`.

https://github.com/extendr/rextendr/blob/c64b0dbd1152c395c82e9191d915c794accc9c27/R/track_rust_source.R#L230-L235

2022-12-22 11:16 UTC, Ilia-Kosenkov commented
Ok, now I see. Perhaps it can later be simplified since we only want to check if wrappers are newer than dll or not.

2022-12-22 15:38 UTC, yutannihilation commented
Thanks for the hint! I replaced it with bare `file.info()`.

2022-12-23 00:29 UTC, yutannihilation commented
Yes, I think so. I was wondering if I can reduce more code, but it seems this is all for now.

2022-12-23 11:16 UTC, Ilia-Kosenkov requested changes
Looks good, thanks!

2022-12-23 11:16 UTC, Ilia-Kosenkov commented on R/register_extendr.R
> +    # As of version 1.4.0, pkgbuild can detect the changes on Rust code.
```suggestion
    # As of version 1.4.0, pkgbuild can detect the changes in Rust code.
```

2022-12-23 12:24 UTC, Ilia-Kosenkov commented
Hm, it blew up because of `{purrr}`. Strange
> DLL 'purrr' not found: maybe not installed for this architecture?

2022-12-23 12:25 UTC, Ilia-Kosenkov approved these changes

2022-12-23 12:30 UTC, yutannihilation commented
Yeah, I have no idea. I hope time will solve...

2022-12-23 12:30 UTC, merged